model_params:
  run_params:
    append_date: False
    outpath: './output/'
    verbose: False
  pds_params:
    pds_variant: 'no'
    pds_targeting: 'perfect'
    pds_borrowing_ability: 'unlimited'
    pds_lending_rate: 0.05
    pds_scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    covered_loss_share: 0.4
scenario_params:
  run_params:
    outpath: './output/'
    force_recompute: False
    verbose: False
    countries: 'all'
    hazards: 'all'
    ppp_reference_year: 2021
  macro_params:
    income_elasticity_eta: 1.5
    discount_rate_rho: .06
    axfin_impact: .1
    ew_year: 2018
    ew_decade: null
    reduction_vul: .2
  hazard_params:
    hazard_protection: 'FLOPROS'
    no_exposure_bias: False
    fa_threshold: .99
  policy_params:
    scale_self_employment:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    scale_non_diversified_income:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    min_diversified_share:
      parameter: 0
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    scale_income:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    scale_liquidity:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
    scale_exposure:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
      scale_total: False
    scale_vulnerability:
      parameter: 1
      scope: ['q1', 'q2', 'q3', 'q4', 'q5']
      scale_total: False
    scale_gini_index:
      parameter: 1
