name: global-socioeconomic-resilience
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.11
  - statsmodels==0.14.0
  - cartopy==0.22.0
  - numpy==1.26.2
  - tqdm==4.65.0
  - scipy==1.11.4
  - pyyaml==6.0.1
  - matplotlib==3.8.0
  - pandas-datareader==0.10.0
  - seaborn==0.13.2
  - geopandas
  - rioxarray==0.15.0
  - requests==2.31.0
  - pandas==2.1.4
  - openpyxl==3.1.5
  - pycountry==24.6.1
  - xarray==2023.6.0
  - ipython
  - jupyter
  - geos[version='>=3.12']
  - shapely
  - conda-forge::pypdf
  - libgdal-netcdf
