model_params:
  run_params:
    append_date: False
    outpath: './results/example'
    verbose: False
  pds_params:
    pds_variant: 'no'
    pds_targeting: 'perfect'
    pds_borrowing_ability: 'unlimited'
    pds_lending_rate: 0.05
    pds_scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    covered_loss_share: 0.4
scenario_params:
  run_params:
    outpath: './results/example'
    recompute: True
    recompute_hazard_protection: False
    download: False
    verbose: False
    countries: 'all'
    exclude_countries: ['THA']
    hazards: 'all'
    ppp_reference_year: 2021
    include_spl: False
    resolution: .2
  macro_params:
    income_elasticity_eta: 1.5
    discount_rate_rho: .06
    axfin_impact: .1
    reduction_vul: .2
#    early_warning_file: "/Users/robin/Documents/Karriere/Jobs/2023_The_World_Bank/03_projects/02_Hydromet/04_code/global-unbreakable-model/data/processed/ew/3__ALL_ODA+SIDS:S+UA_ew.csv"
  hazard_params:
    hazard_protection: 'FLOPROS'
    no_exposure_bias: False
    fa_threshold: .99
  policy_params:
    scale_self_employment:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_non_diversified_income:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    min_diversified_share:
      parameter: 0
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_income:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_liquidity:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_exposure:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
      scale_total: False
    scale_vulnerability:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
      scale_total: False
    scale_gini_index:
      parameter: 1
